config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :password, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
    @user = User.new(user_params)
    if @user.save
      redirect_to new_user_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to edit_user_path(params[:id])
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with url: user_path , method: 'patch', model: @user do |form| %>
  <div>
    <% @user.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <%end%>
  </div>
  <%= form.label :username, 'Username:'%>
  <%= form.text_field :username, placeholder: 'Your username' %>
  <%= form.label :email, 'Email:'%>
  <%= form.email_field :email, placeholder: 'example@email.com' %>
  <%= form.label :password, 'Password:'%>
  <%= form.password_field :password, placeholder: '************' %>
  <%= form.submit %>
<%end%>

app/views/users/new.html.erb
<%
=begin%>
 <form accept-charset="UTF-8" action = '/users' method = 'post'>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for = 'username'>Username</label>
  <input type = 'text' name = 'user[username]'>
  <label for = 'email'>Email:</label>
  <input type = 'email' name = 'user[email]'>
  <label for = 'password'>password:</label>
  <input type = 'password' name = 'user[password]'>
  <input type = 'submit' value = 'submit'>
</form> 
<%
=end%>

<%
=begin%>
 <%= form_tag("/users", method: 'post') do%>
<%= label(:user, :username) %>
<%= text_field(:user, :username)%>
<%= label(:user, :email)%>
<%= email_field(:user, :email)%>
<%= label(:user, :password)%>
<%= password_field(:user, :password)%>
<%= submit_tag %>
<% end %> 
<%
=end%>

<%= form_with url: users_path, method: 'post', model: @user do |form| %>
  <div>
    <% @user.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <%end%>
  </div>
  <%= form.label :username, 'Username:'%>
  <%= form.text_field :username, placeholder: 'Your username' %>
  <%= form.label :email, 'Email:'%>
  <%= form.email_field :email, placeholder: 'example@email.com' %>
  <%= form.label :password, 'Password:'%>
  <%= form.password_field :password, placeholder: '************' %>
  <%= form.submit %>
<%end%>